name: Require team membership
description: Fails unless the triggering user is an active member of the given org/team

inputs:
  org_slug:
    description: GitHub organization login/slug (e.g. my-org)
    required: true
  team_slug:
    description: GitHub team slug (e.g. devops)
    required: true
  job_name:
    description: The job calling the action (display name)
    required: true
  github_org_access_token:
    description: A GitHub token with the `read:org` permission
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify commenter is in the team
      id: auth
      uses: actions/github-script@v7
      env:
        ORG_SLUG: ${{ inputs.org_slug }}
        TEAM_SLUG: ${{ inputs.team_slug }}
        JOB_NAME: ${{ inputs.job_name }}
      with:
        github-token: ${{ inputs.github_org_access_token }}
        script: |
          const org = process.env.ORG_SLUG;
          const team_slug = process.env.TEAM_SLUG;
          const username = context.payload.comment.user.login;

          core.setOutput("authorized", "false");
          core.setOutput("error", "");

          if (!context.payload.issue.pull_request) {
            core.setOutput("error", "This command only works on pull requests.");
            return;
          }

          try {
            const res = await github.rest.teams.getMembershipForUserInOrg({
              org,
              team_slug,
              username,
            });

            const state = res.data.state; // "active" or "pending"
            if (state === "active") {
              core.setOutput("authorized", "true");
            } else {
              core.setOutput(
                "error",
                `User @${username} is not an active member of @${org}/${team_slug} (state=${state}).`
              );
            }
          } catch (err) {
            const status = err.status ? `${err.status}` : "unknown";
            const msg = err.message ? `${err.message}` : `${err}`;

            // 404 is ambiguous: could be "not a member", "team/org not found", OR "token can't see membership"
            if (`${status}` === "404") {
              core.setOutput(
                "error",
                `Cannot verify membership for @${username} in @${org}/${team_slug}. ` +
                `GitHub returned 404. This can mean the user is not a member, the team/org slug is wrong, ` +
                `or the token cannot read org/team membership.`
              );
              return;
            }

            core.setOutput(
              "error",
              `Cannot verify membership for @${username} in @${org}/${team_slug}. ` +
              `GitHub API error: ${status} ${msg}`
            );
          }

    - name: Comment authorization error
      if: steps.auth.outputs.authorized != 'true'
      uses: actions/github-script@v7
      env:
        ORG_SLUG: ${{ inputs.org_slug }}
        TEAM_SLUG: ${{ inputs.team_slug }}
        JOB_NAME: ${{ inputs.job_name }}
      with:
        # For commenting on the PR, the normal workflow token is fine
        github-token: ${{ github.token }}
        script: |
          const owner = context.repo.owner;
          const repo  = context.repo.repo;
          const prNumber = context.payload.issue.number;
          const username = context.payload.comment.user.login;

          const org = process.env.ORG_SLUG;
          const team_slug = process.env.TEAM_SLUG;
          const job_name = process.env.JOB_NAME;

          const error = `${{ steps.auth.outputs.error }}`.trim();
          const body =
            `⚠️ OpenTofu plan was **not** started.\n\n` +
            `**Job:** ${job_name}\n` +
            `**Triggered by:** @${username}\n` +
            `**Reason:** ${error || "User is not authorized to run this command."}\n\n` +
            `Only members of **@${org}/${team_slug}** may run \`tofu plan\`.`;

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: prNumber,
            body
          });

    - name: Stop if unauthorized
      if: steps.auth.outputs.authorized != 'true'
      shell: bash
      run: |
        echo "Not authorized to run tofu plan"
        exit 1
